# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11.13
        environment:
          ENV: CI
          GO111MODULE: "on"
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/creds.json

    steps:
      - checkout
      - run: echo $TEST_GOOGLE_CREDENTIALS | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
      - run: go get -v -t -d ./...
      - run: go test -v ./...
